# Smoke Test Training Hyperparameters
epochs: 1
batch: 1
imgsz: 640
device: 'cpu'
save: true
exist_ok: true
pretrained: true
optimizer: auto
verbose: true
seed: 42
deterministic: true
amp: false
project: 'experiments'
name: 'test_train'
